filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*-json.log

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - add_host_metadata: ~
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["http://es01:9200"]

setup.kibana:
  host: "http://kib01:5601"